stages:
  - build # dependancies
  - pester # pester test script
  - test_pwsh # test powershell core latest
  - test_powershell # test powershell
  - deploy_psprivate # deploy to psgallary private instance
  - deploy_psgallary # deploy to psgallary
build-job:
  stage: build
  script:
    - pwsh.exe
    - write-host -f green "template ci\cd config successfull"
pester-job:
  stage: pester
  script:
    - pwsh.exe
    - write-host -f green "template ci\cd config successfull"
test-pwsh-job:
  stage: test_pwsh
  script:
    - pwsh.exe
    - write-host -f green "template ci\cd config successfull"
test-powershell-job:
  stage: test_powershell
  script:
    - powershell.exe
    - write-host -f green "template ci\cd config successfull"
psgallary-deploy-job:
  stage: deploy_psgallary
  script:
    - pwsh.exe
psprivate-deploy-job:
  stage: deploy_psprivate
  script:
    - pwsh.exe
    - write-host -f green "template ci\cd config successfull"
#include:
#  - template: auto-devops.gitlab-ci.yml
